// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-_v7wtoPO2wE_-3Yde9pZa1x10Pgvzsg',
    appId: '1:320430392676:web:8d50cb90050b0d901d6671',
    messagingSenderId: '320430392676',
    projectId: 'authentication-1ab5a',
    authDomain: 'authentication-1ab5a.firebaseapp.com',
    storageBucket: 'authentication-1ab5a.firebasestorage.app',
    measurementId: 'G-4RPT8VCSYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVd5qoz20KOWP0dvnPsKAwnYK_TlVAass',
    appId: '1:320430392676:android:36122f1e91a7cca41d6671',
    messagingSenderId: '320430392676',
    projectId: 'authentication-1ab5a',
    storageBucket: 'authentication-1ab5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq_ow_iEMyNxpogyGz78INoRTYe8jfrMg',
    appId: '1:320430392676:ios:74fb93d626c8bd4b1d6671',
    messagingSenderId: '320430392676',
    projectId: 'authentication-1ab5a',
    storageBucket: 'authentication-1ab5a.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq_ow_iEMyNxpogyGz78INoRTYe8jfrMg',
    appId: '1:320430392676:ios:74fb93d626c8bd4b1d6671',
    messagingSenderId: '320430392676',
    projectId: 'authentication-1ab5a',
    storageBucket: 'authentication-1ab5a.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-_v7wtoPO2wE_-3Yde9pZa1x10Pgvzsg',
    appId: '1:320430392676:web:a0701fff75be41701d6671',
    messagingSenderId: '320430392676',
    projectId: 'authentication-1ab5a',
    authDomain: 'authentication-1ab5a.firebaseapp.com',
    storageBucket: 'authentication-1ab5a.firebasestorage.app',
    measurementId: 'G-JDLR3FZJ92',
  );
}
